export const PAYMENT_STATUS = {
  PAY_STANDBY: 'PAY_STANDBY',
  PAY_APPROVED: 'PAY_APPROVED',
  PAY_CANCEL: 'PAY_CANCEL',
  PAY_PROGRESS: 'PAY_PROGRESS',
  PAY_COMPLETE: 'PAY_COMPLETE',
  ESCROW_REQUEST: 'ESCROW_REQUEST',
  ESCROW_RELEASE: 'ESCROW_RELEASE',
  ESCROW_DENY: 'ESCROW_DENY',
  REFUND_PROGRESS: 'REFUND_PROGRESS',
  REFUND_SUCCESS: 'REFUND_SUCCESS',
  SETTLEMENT_COMPLETE: 'SETTLEMENT_COMPLETE',
  SETTLEMENT_REFUND_COMPLETE: 'SETTLEMENT_REFUND_COMPLETE'
}